---
kind: pipeline
name: Run Ansible

platform:
  os: linux
  arch: arm64

steps:
- name: check ansible syntax
  image: plugins/ansible:1
  settings:
    playbook: playbooks/docker.yml
    inventory: hosts
    syntax_check: true
  when:
    event:
    - push
    - pull_request

- name: apply ansible playbook
  image: ansible-docker-aarch64:latest
  pull: never
  commands:
    - mkdir ~/.ssh
    - echo "$ansible_private_key" > $HOME/.ssh/id_rsa
    - chmod 600 $HOME/.ssh/id_rsa
    - ansible-playbook --private-key="$HOME/.ssh/id_rsa" playbooks/docker.yml
  when:
    event:
    - push
    - tag
