---
kind: pipeline
name: Run Ansible

platform:
  os: linux
  arch: arm64

steps:
- name: check ansible syntax
  image: plugins/ansible:1
  settings:
    playbook: playbooks/docker.yml
    inventory: hosts
    syntax_check: true
  when:
    event:
    - push
    - pull_request

- name: apply ansible playbook
  image: ansible-docker-aarch64:latest
  pull: never
  environment:
    SSH_KEY:
      from_secret: ansible_private_key
    VAULT_PASS:
      from_secret: vault_password
  commands:
    - mkdir ~/.ssh
    - echo "$SSH_KEY" > $HOME/.ssh/id_rsa
    - chmod 600 $HOME/.ssh/id_rsa
    - echo "$VAULT_PASS" > vault_password
    - ansible-playbook playbooks/docker.yml
  when:
    event:
    - push
    - tag
