kind: pipeline
name: default

steps:
- name: check ansible syntax
  image: plugins/ansible:1
  settings:
    playbook: playbooks/docker.yml
    galaxy: requirements.yml
    inventory: hosts
    syntax_check: true
  when:
    event:
    - pull_request

#- name: apply ansible playbook
#  image: plugins/ansible:1
#  environment:
#  settings:
#    playbook: playbooks/docker.yml
#    galaxy: requirements.yml
#    inventory: hosts
#    private_key:
#      from_secret: ansible_private_key
#    vault_password:
#      from_secret: ansible_vault_password
#  when:
#    event:
#    - push
#    - tag
#
