- name: Stop PhotoPrism if it's currently running
  changed_when: False
  ansible.builtin.command:
    argv: ["/bin/bash", "/var/www/photoprism/service.sh", "stop"]
    chdir: "/var/www/photoprism"
    removes: "/var/www/photoprism/service.sh"

- name: Copy PhotoPrism service files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop: [
    {"src": "docker-compose.yml.j2", "dest": "/var/www/photoprism/docker-compose.yml", "owner": "root", "mode": "600"},
    {"src": "service.sh.j2", "dest": "/var/www/photoprism/service.sh", "owner": "root", "mode": "755"}
  ]

- name: Update PhotoPrism
  changed_when: False
  ansible.builtin.command:
    argv: ["/bin/bash", "/var/www/photoprism/service.sh", "update"]
    chdir: "/var/www/photoprism"

- name: Bring PhotoPrism up
  changed_when: False
  ansible.builtin.command:
    argv: ["/bin/bash", "/var/www/photoprism/service.sh", "start"]
    chdir: "/var/www/photoprism"

- name: Schedule a library scan at 1 AM every day
  cron:
    name: Scan the PhotoPrism library
    hour: "1"
    job: "/usr/bin/docker exec photoprism_photoprism_1 /photoprism/bin/photoprism index"
