---
- name: Add Crowdsec GPG apt Key
  apt_key:
    url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
    state: present

- name: Add Crowdsec Repository
  apt_repository:
    repo: deb https://packagecloud.io/crowdsec/crowdsec/ubuntu bionic stable
    state: present
    
- name: Update apt and install Crowdsec and Prometheus
  apt: 
    update_cache: yes 
    name:
      - crowdsec
      - crowdsec-cloudflare-bouncer
      - prometheus
    state: present

- name: cscli hub update
  command:
    cmd: cscli hub update
  changed_when: false
    
- name: Install the necessary collections
  command:
    cmd: "sudo cscli collections install crowdsecurity/{{ item }}"
  with_items:
    - nginx
    - sshd
    - linux
    - iptables
  register: collections_install_result
  changed_when: "'overwrite' not in collections_install_result.stderr"

- name: Setup cloudflare bouncer
  command:
    cmd: "sudo crowdsec-cloudflare-bouncer -g {{ cloudflare_token }} -o /etc/crowdsec/bouncers/crowdsec-cloudflare/bouncer.yaml"

- name: Send IP lists to cloudflare
  command:
    cmd: "sudo crowdsec-cloudflare-bouncer -s"

- name: Enable the Prometheus endpoint
  lineinfile:
    path: "/etc/crowdsec/config.yaml"
    line: "  enabled: true"
    search_string: "enabled: false"
    insertafter: "^prometeus:.*$"
  notify:
    - Restart prometheus
    - Restart crowdsec

- name: Increase ban time
  replace:
    path: "/etc/crowdsec/profiles.yaml"
    regexp: 'duration: [0-9]h'
    replace: 'duration: 999h'
  notify:
    - Restart crowdsec

- name: Start and enable Crowdsec services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
      - crowdsec
      - crowdsec-cloudflare-bouncer
      - prometheus
