- name: Stop Vaultwarden if it's currently running
  changed_when: False
  ansible.builtin.command:
    argv: ["./service.sh", "stop"]
    chdir: "/var/www/vaultwarden"
    removes: "./service.sh"

- name: Copy Vaultwarden service files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop: [
    {"src": "vaultwarden/docker-compose.yml.j2", "dest": "/var/www/vaultwarden/docker-compose.yml", "owner": "root", "mode": "600"},
    {"src": "vaultwarden/service.sh.j2", "dest": "/var/www/vaultwarden/service.sh", "owner": "root", "mode": "755"}
  ]

- name: Update Vaultwarden
  changed_when: False
  ansible.builtin.command:
    argv: ["./service.sh", "update"]
    chdir: "/var/www/vaultwarden"

- name: Bring Vaultwarden up
  changed_when: False
  ansible.builtin.command:
    argv: ["./service.sh", "start"]
    chdir: "/var/www/vaultwarden"

